/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as CreateTaskImport } from './routes/create-task'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const CreateTaskRoute = CreateTaskImport.update({
  id: '/create-task',
  path: '/create-task',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/create-task': {
      id: '/create-task'
      path: '/create-task'
      fullPath: '/create-task'
      preLoaderRoute: typeof CreateTaskImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/create-task': typeof CreateTaskRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/create-task': typeof CreateTaskRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/create-task': typeof CreateTaskRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/create-task'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/create-task'
  id: '__root__' | '/' | '/create-task'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CreateTaskRoute: typeof CreateTaskRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreateTaskRoute: CreateTaskRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/create-task"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/create-task": {
      "filePath": "create-task.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
